export { isBankCard } from "./isBankCard";
export { isChinese } from "./isChinese";
export { isChineseName } from "./isChineseName";
export { isEmail } from "./isEmail";
export { isEnglishName } from "./isEnglishName";
export { isHexColor } from "./isHexColor";
export { isIDCard } from "./isIDCard";
export { isIMEI } from "./isIMEI";
export { isIPnPort } from "./isIPnPort";
export { isMagnetLink } from "./isMagnetLink";
export { isNoWord } from "./isNoWord";
export { isNumAndStr } from "./isNumAndStr";
export { isPhoneNum } from "./isPhoneNum";
export { isPlateNum } from "./isPlateNum";
export { isPostalCode } from "./isPostalCode";
export { isThunderLink } from "./isThunderLink";
export { isUnixFilePath } from "./isUnixFilePath";
export { isUnixFolderPath } from "./isUnixFolderPath";
export { isUrl } from "./isUrl";
export { isWechatId } from "./isWechatId";
export { isWindowsFilePath } from "./isWindowsFilePath";
export { isWindowsFolderPath } from "./isWindowsFolderPath";
declare const _default: {
    isBankCard: (value: string) => boolean;
    isChinese: (value: string) => boolean;
    isChineseName: (value: string) => boolean;
    isEmail: (value: string) => boolean;
    isEnglishName: (value: string) => boolean;
    isHexColor: (value: string) => boolean;
    isIDCard: (value: string) => boolean;
    isIMEI: (value: string) => boolean;
    isIPnPort: (value: string) => boolean;
    isMagnetLink: (value: string) => boolean;
    isNoWord: (value: string) => boolean;
    isNumAndStr: (value: string) => boolean;
    isPhoneNum: (value: string) => boolean;
    isPlateNum: (value: string) => boolean;
    isPostalCode: (value: string) => boolean;
    isThunderLink: (value: string) => boolean;
    isUnixFilePath: (value: string) => boolean;
    isUnixFolderPath: (value: string) => boolean;
    isUrl: (value: string) => boolean;
    isWechatId: (value: string) => boolean;
    isWindowsFilePath: (value: string) => boolean;
    isWindowsFolderPath: (value: string) => boolean;
};
export default _default;
